### ISSUE TITLE
Building examples from README.md fails

### ISSUE THREAD

**Issue by sj4nes** [janestreet/incr_dom#12]
Assuming that `jbuilder` is actually `dune` now, the README at

https://github.com/janestreet/incr_dom/blob/master/example/README.org

```sh
jbuilder build example/incr_decr/{main.bc.js,index.html}
```
fails.

When I run:
```sh
dune build example/incr_decr/{main.bc.js,index.html}
Error: Don't know how to build example/incr_decr/main.bc.js
```
Information about incr_dom/opam/ocaml installation:
```sh
❯ opam list | grep incr_dom
incr_dom                      v0.13.0          A library for building dynamic webapps, using Js_of_ocaml

❯ opam --version
2.0.5

❯ ocaml --version
The OCaml toplevel, version 4.10.0
```

**Comment by TyOverby** [comment]
Could you follow these instructions and see if they work? https://dune.readthedocs.io/en/stable/jsoo.html

**Comment by liweijian** [comment]
Actually I could build the example when I cloned the incr_dom repo and built inside it as follows:

```
~/D/t/n/incr_dom (master|✔) $ dune build example/text_input/bin/{main.bc.js,index.html}
~/D/t/n/incr_dom (master|✔) $ open _build/default/example/text_input/bin/index.html
```

However, when I try to build outside the repo, I got the same error:

```
~/D/t/incre101 [1] $ dune build bin/{main.bc.js,index.html}
Error: Don't know how to build bin/main.bc.js
```

In the later case, I copied the text_input example to another directory and renamed it to `incre101`

**Comment by TyOverby** [comment]
@liweijian: When you build it outside the repo, are you copying the example directory?

Would you be able to build a repo that reproduces the behavior?

**Comment by liweijian** [comment]
Thanks for your reply @TyOverby 

I believe that it's easy to reproduce the behavior:

```shell
$ git clone git@github.com:janestreet/incr_dom.git
 $ cp -r incr_dom/example/hello_world .
$ ls
hello_world/ incr_dom/

$ cd hello_world/
$ dune build bin/{main.bc.js,index.html}
Info: Creating file dune-project with this contents:
| (lang dune 2.7)
Error: Don't know how to build bin/main.bc.js
Done: 0/0 (jobs: 0)⏎
```

**Comment by TyOverby** [comment]
Oh man, that's confusing.  I was able to reproduce this on my laptop; and the solution was to put `(modes js)` in `bin/dune`.  I think that you don't need this if you've got a `dune-project` file that forces back-compat with an older dune syntax.  [This is why](https://github.com/janestreet/incr_dom/blob/master/dune-project) the code will build if it's done inside of the incr_dom repo!

**Comment by TyOverby** [comment]
@liweijian: can I infer from your 👍 reaction that this fixed the problem for you?

**Comment by liweijian** [comment]
> @liweijian: can I infer from your 👍 reaction that this fixed the problem for you?

Yup, awesome thanks 💯
